version: '3'
services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    command: >
      sh -c "npx prisma migrate dev --name init && npm start"
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: spending
    ports:
      - "5433:5432"
    volumes:
      - ./data:/var/lib/postgresql/data